config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "homes#about"

  devise_for :users,
    skip: [:passwords, :registrations], # いらないルーティングを作らない。sessionとregistration新規のみ。
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_up" => "devise/registrations#new", as: "new_user_registration"
    post "users" => "devise/registrations#create", as: "user_registration"
  end

  resources :users, only:[:show, :edit, :update], param: :account_name # ランダム文字列をidの代わりに使用

  get "jobs/search" => "jobs#search", as: "job_search"
  get "jobs/draft_index" => "jobs#draft_index", as: "job_draft_index"
  resources :jobs, only:[:show, :new, :create, :edit, :update, :destroy], param: :rondom_id # ランダム文字列をidの代わりに使用

  resource :bookmarks, only:[:create,:destroy]
  get "bookmarks" => "bookmarks#index", as: "bookmark_index"
  # resourceだとindexアクションが生成されないため自作。"bookmarks_path"を使おうとするとエラーになるため名前も自作。

  resource :offers, only:[:create,:destroy]
  get "offers" => "offers#index", as: "offers_index"
  # resourceだとindexアクションが生成されないため自作。"offers_paths"を使おうとするとエラーになるため名前も自作。

  resources :chatrooms, only:[:index, :show, :create, :destroy], param: :rondom_id do
    get "change_hide" => "chatrooms#change_hide", as: "change_hide"
  end# ランダム文字列をidの代わりに使用
  resources :messages,only:[:create]

  get "*unmatched_route", to: "application#routing_error", format: false, constraints: lambda { |r|
    # 'rails/active_storage'が含まれているパスはリダイレクト対象外にする
    r.path.exclude? "rails/active_storage"
  }
end

app/views/layouts/modals/_logout_modal.html.slim
#Logoutmodal.modal.fade[aria-hidden="true"]
  .modal-dialog.modal-dialog-centered
    .modal-content
      .pt-4
        h5.text-center
          strong
            | ログアウトしますか？
      .modal-footer
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-rounded"
        button.btn.btn-secondary.btn-rounded[type="button" data-dismiss="modal"]
          | 今はしない

app/views/layouts/modals/_search_modal.html.slim
#searchModal.modal.fade[aria-hidden="true"]
  .modal-dialog.modal-dialog-centered
    .modal-content.bg-light
      .pt-4
        h2.text-center
          strong
            | どんなバイトがしたい？
            
      = form_with url: job_search_path, method: :get do |f|

        .modal-body.px-5
          = f.label :job_type ,"ジャンル"
          = f.select :job_type, Job.job_types.keys, { include_blank: '指定しない'}, { class: 'form-control mb-4' }

          = f.label :prefecture_code ,"地域（都道府県）"
          = f.select :prefecture_code, Job.prefecture_codes.keys, { include_blank: '指定しない'}, { class: 'form-control mb-4' }

          = f.label :key_word,"キーワード"
          = f.text_field :key_word,  class: "form-control mb-3", placeholder: "キーワードを入力"

          = f.check_box :include_sample,:as => :boolean, checked: false, class: "form-check-input mb-4"
          = f.label :include_sample, "サンプルを検索結果に含めない"

        .modal-footer
          = f.submit "この条件でさがす", class: "btn btn-primary btn-rounded"
           button.btn.btn-secondary.btn-rounded[type="button" data-dismiss="modal"]
            | 閉じる