config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "homes#about"

  devise_for :users,
    skip: [:passwords, :registrations], # いらないルーティングを作らない。sessionとregistration新規のみ。
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_up" => "devise/registrations#new", as: "new_user_registration"
    post "users" => "devise/registrations#create", as: "user_registration"
  end

  resources :users, only:[:show, :edit, :update], param: :account_name # ランダム文字列をidの代わりに使用

  get "jobs/search" => "jobs#search", as: "job_search"
  get "jobs/draft_index" => "jobs#draft_index", as: "job_draft_index"
  resources :jobs, only:[:show, :new, :create, :edit, :update, :destroy], param: :rondom_id # ランダム文字列をidの代わりに使用

  resource :bookmarks, only:[:create,:destroy]
  get "bookmarks" => "bookmarks#index", as: "bookmark_index"
  # resourceだとindexアクションが生成されないため自作。"bookmarks_path"を使おうとするとエラーになるため名前も自作。

  resource :offers, only:[:create,:destroy]
  get "offers" => "offers#index", as: "offers_index"
  # resourceだとindexアクションが生成されないため自作。"offers_paths"を使おうとするとエラーになるため名前も自作。

  resources :chatrooms, only:[:index, :show, :create, :destroy], param: :rondom_id do
    get "change_hide" => "chatrooms#change_hide", as: "change_hide"
  end# ランダム文字列をidの代わりに使用
  resources :messages,only:[:create]

  get "*unmatched_route", to: "application#routing_error", format: false, constraints: lambda { |r|
    # 'rails/active_storage'が含まれているパスはリダイレクト対象外にする
    r.path.exclude? "rails/active_storage"
  }
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
    geocoded_by :other_address
    after_validation :geocode, if: :other_address_changed? # 住所が入って保存されたら緯度経度を入れる

    belongs_to :user
    has_many :bookmarks, dependent: :destroy
    has_many :offers, dependent: :destroy
    has_many :chatrooms, dependent: :destroy

    has_one_attached :image

    # バリデーション。
    with_options on: :release do
      validates :tytle, length: { minimum: 1, maximum: 30}
      validates :job_type, presence: true
      validates :introduction, length: { minimum: 1, maximum: 3000}
      validates :prefecture_code, presence: true
      validates :other_address, presence: true
      validates :postal_code, format: {with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}$|^\d{5}$|^\d{7}\z/}# 半角数字７桁のみ。ハイフン有り無しok,
      validates :hourly_wage_before_type_cast, format: {with: /\A[0-9]+\z/}# 半角数字のみ
    end



  # 画像を表示させるメソッド。画像がない場合にはnoimageを表示させる。
  def get_image(width,height)
    unless image.attached?
      image_number = rand(1..4)

      file_path = Rails.root.join("app/assets/images/noimage_job(#{image_number}).png")
      image.attach(io: File.open(file_path), filename: "noimage_job.jpg", content_type: "image/png")
    end
   # 指定サイズにリサイズ、中心を基準点にして、指定サイズに切り抜く。
    image.variant(resize: "#{width}x#{height}^", gravity: :center, crop: "#{width}x#{height}+0+0").processed
  end

  # current_userにブックマークされているか確認するメソッド。ビューの表示分岐で使う
  def keeped_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

  # current_userが送ったオファーが存在するか確認するメソッド。ビューの表示分岐で使う
  def offerd_by?(user)
    offers.exist?(user_id: user.id)
  end


  # 最寄り駅を取得して保存するメソッド
  def addStation
    uri = URI.parse("http://express.heartrails.com/api/json?method=getStations&x=#{self.longitude}&y=#{self.latitude}")
    response = Net::HTTP.get_response(uri)
    result = JSON.parse(response.body)
    self.near_station = result["response"]["station"][0]["name"] unless result["response"]["station"].blank?
    self.near_station_line =  result["response"]["station"][0]["line"] unless result["response"]["station"].blank?
    # 再度保存する
    self.save
  end

  before_create :set_rondom_id # ユーザー作成時に以下のアクション
  # rondom_idが空か、同じrondom_idのユーザーが存在する時にランダムな文字列を代入する
    def set_rondom_id
      while self.rondom_id.blank? || Job.find_by(rondom_id: self.rondom_id).present? do
        self.rondom_id = SecureRandom.base36
      end
    end
    def to_param
       rondom_id
    end


   enum job_type: {
    飲食・フードサービス:0,営業・販売:1,旅行・レジャー・イベント:2,倉庫・物流・生産管理:3,警備・保安:4,
    経営・事業企画・人事・事務:5,マーケティング・広告・宣伝:6,保育士・教員・講師:7,ドライバー・引越し作業員:8,
    介護・福祉:9,医療・看護師・薬剤師:10,メディア・クリエイター:11,IT・Web・ゲームエンジニア:12,
    エンジニアリング・設計開発:13,整備・修理:14,清掃・美化:15,ビューティ・生活サービス:16,建設・土木・施工:17,
    製造・工場:18,金融・財務・会計:19,法務・法律:20,研究:21,農林漁業:22,
  }

   enum prefecture_code: {
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47 }
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :ensure_user, only:[:edit, :update, :destroy]
  before_action :set_job, only:[:show, :edit, :update, :destroy]
  
  def new
    @job=Job.new
    @renderd = "renderd"
  end

  def create
    job=Job.new(job_params)
    job.user = current_user
    job.near_station_line = ""
    job.near_station = "" # 一度保存しないとgeocoderが動かないため最寄り駅空欄でいったん保存
    if params[:post] # 投稿する場合
      if job.save(context: :release)
        # 最寄り駅情報を取得して再保存
        job.addStation
        redirect_to job_path(job),flash: {notice: "募集を公開しました"}
      else
        @job = job
        flash.now[:error] = "作成に失敗しました"
        render :new
      end
    else  # 下書きの場合
      if job.update(released: false)
        redirect_to job_draft_index_path, flash: {notice: "募集を下書き保存しました！"}
      else
        @job=job
        flash.now[:error] = "下書き保存に失敗しました"
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    job=Job.find_by(rondom_id: params[:rondom_id])
    if params[:post] # 投稿する場合
        @job.attributes = job_params # updateにcontextが適用できないためattributeで代入してからsave
        @job.released = true
        if @job.save(context: :release)
          # 最寄り駅情報を取得して代入
          @job.addStation
          redirect_to job_path(job),flash: {notice: "募集を公開しました"}
        else
          flash.now[:error] = "公開できませんでした"
          render :edit
        end
    elsif params[:draft] # 下書きにする場合
        @job.released = false
        if @job.update(job_params)
          redirect_to job_draft_index_path, flash: {notice: "募集を下書き保存しました"}
        else
          flash.now[:error] = "下書き保存に失敗しました"
          render :edit
        end
    end
  end


  def destroy
    if @job.destroy
      redirect_to user_path(current_user), flash: {notice: "募集を削除しました"}
    else
      flash.now[:error] = "削除できませんでした"
      render :edit
    end
  end
  
  #下書き一覧
  def draft_index
    @jobs = current_user.jobs.where(released: false).all
    @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(5) # ページネーション（無限スクロール用）
  end


  def search
    @jobs = Job.where(released: true).all
    # 各条件が存在する場合のみ絞り込む
    @jobs = @jobs.where(prefecture_code: params[:prefecture_code]) if params[:prefecture_code].present?
    @jobs = @jobs.where(job_type: params[:job_type]) if params[:job_type].present?
    @jobs = @jobs.where("tytle LIKE(?) or introduction LIKE(?)","%#{params[:key_word]}%","%#{params[:key_word]}%") if params[:key_word].present?
    @jobs = @jobs.where.not("introduction LIKE(?)", "%【この情報はサンプルです】%" ) if params[:include_sample] == "1" # チェックボックスが選択されていたらサンプルを除外
    @jobs = Kaminari.paginate_array(@jobs).page(params[:page]).per(5) # ページネーション（無限スクロール用）
    render :index
  end

private
  def job_params
    params.require(:job).permit(:rondom_id, :tytle, :job_type, :image, :introduction, :hourly_wage, :postal_code, :prefecture_code, :other_address ,:near_station, :near_station_line)
  end
  
  #jobをランダムIDで特定
  def set_job
    @job=Job.find_by(rondom_id: params[:rondom_id])
  end
  
  # 自分の投稿以外は編集不可
  def ensure_user
    job=Job.find_by(rondom_id: params[:rondom_id])
    unless job.user == current_user
      redirect_back fallback_location: user_path(current_user), flash: {error: "権限がありません。"}
    end
  end
end

app/views/jobs/_index.html.slim
.job-index.jscroll
  - jobs.each do |job|

    /公開中の場合。仕事詳細へのリンク
    - if job.released == true
      = link_to job_path(job), data: {"turbolinks" => false}  do
        .card.index_card.text-body
          .row
            .d-none.d-md-block.col-md-5
              = image_tag job.get_image(1000,1000), class: "rounded-start img-thumbnail index_card_image h-100 w-100"
            .col-12.col-md-7.my-4.mx-auto.my-auto.py-5
                .row.justify-content-center
                  h3.text-center
                    strong
                      = job.tytle
                  small.text-center.col-10
                    = job.near_station
                    | 駅 /
                    = job.job_type
                    |  / 時給：
                    = job.hourly_wage
                    | 円
                  h6.mt-3.p-4.border.rounded-8.bg-light.col-9
                    = job.introduction.truncate(70)
                .row
                  .col-2.offset-1
                    = image_tag job.user.get_image(70,70), class: 'rounded-circle img-thumbnail'
                  small.col-9.d-flex.align-items-center
                    = job.user.name
                    br
                    = job.user.age
                    | 歳&emsp;
                    = job.user.sex
                    |&emsp;
                    = job.user.prefecture

    /下書き一覧の場合。直接編集画面に遷移させる
    - else
      = link_to edit_job_path(job), data: {"turbolinks" => false}  do
        .card.index_card.text-body
          .row
            .d-none.d-md-block.col-md-5
              = image_tag job.get_image(500,500), class: "img-fluid rounded-start img-thumbnail index_card_image h-100 w-100"
            .col-12.col-md-7.my-4.mx-auto.my-auto.py-5

              .row.justify-content-center

                h3.text-center
                  strong
                    = job.tytle
                small.text-center
                  = job.near_station
                  | 駅 /
                  = job.job_type
                  |  / 時給：
                  = job.hourly_wage
                  | 円
                h6.text-center.mt-3.p-4.border.rounded-8.bg-light.col-9
                  = job.introduction.truncate(70)

  /ページネーション。無限スクロール用に非表示
  .d-none
    = paginate jobs

/jscroll呼び出し
= render "jobs/js/jscroll"

app/views/jobs/_info.html.slim
.card.my-5.py-5
  .row.justify-content-center
    .col-9
      /新規作成と変種時でビューを分岐させる
      - if action_name == 'new' or action_name == 'create'
        h3.text-center.text-nowrap
          strong
            | パートナーを募集しよう
      - else
        h3.text-center.text-nowrap
          strong
            | 仕事情報を編集

      = form_with model: @job do |f|
        .container

          .row.align-items-center.my-4
            /新規作成と変種時でビューを分岐させる
            - if action_name == 'new' or action_name == 'create'
              = f.label :image do
                = image_tag "noimage_job(#{rand(1..4)}).png", class: 'avatar img-thumbnail w-100',size: "300x300"
                = f.file_field :image, class: 'uploader d-none'
            - else
              = f.label :image do
                = image_tag @job.get_image(1500,1500), class: 'avatar img-thumbnail w-100' ,size: "300x300"
                = f.file_field :image, class: 'uploader d-none'
            p
              | クリックで紹介画像を追加
              br
              small
                | (変更しない場合はランダムになります)

          .row.align-items-center.mb-4
            = f.label :tytle ,"タイトル"
            = f.text_field :tytle, class: "form-control", placeholder: "募集タイトル"
            - if @job.errors.include?(:tytle)
              small.text-danger.text-nowrap
                = @job.errors.full_messages_for(:tytle).first

          .row.align-items-center.mb-4
            = f.label :job_type ,"職種"
            = f.select :job_type, Job.job_types.keys, { include_blank: '選択'}, { class: 'form-control w-75 text-muted'}
            - if @job.errors.include?(:job_type)
              small.text-danger.text-nowrap
                = @job.errors.full_messages_for(:job_type).first

          .row.align-items-center.mb-4
            = f.label :introduction,"紹介文"
            = f.text_area :introduction, class: "introduction form-control", placeholder: "仕事の詳細やアピールポイントなど", size: "10x5"
            small.text-count.text-success
            br
            - if @job.errors.include?(:introduction)
              small.text-danger.text-nowrap
                = @job.errors.full_messages_for(:introduction).first

          .row.align-items-center.mb-4
            = f.label :hourly_wage,"時給", class: "col-12"
            = f.text_field :hourly_wage, class: "form-control w-75 ", placeholder: "半角数字"
            | 円
            - if @job.errors.include?(:hourly_wage_before_type_cast)
              small.text-danger.text-nowrap
                = @job.errors.full_messages_for(:hourly_wage_before_type_cast).first

          .row.align-items-center.mb-4
            = f.label :postal_code, "郵便番号"
            = f.text_field :postal_code, class: "postal_code form-control w-75", placeholder: "0000000"
            - if @job.errors.include?(:postal_code)
              small.text-danger.text-nowrap
                = @job.errors.full_messages_for(:postal_code).first

          .row.align-items-center.mb-4
            = f.label :prefecture_code, "所在地（都道府県）"
            br
            = f.select :prefecture_code, Job.prefecture_codes.keys, { include_blank: '選択'}, { class: 'prefecture_code form-control w-75 text-muted' }
            - if @job.errors.include?(:prefecture_code)
              small.text-danger.text-nowrap
                = @job.errors.full_messages_for(:prefecture_code).first

          .row.align-items-center.mb-4
            = f.label :other_address, "市区町村以降の住所"
            = f.text_field :other_address, class: "other_address form-control w-100", placeholder: "住所を入力"
            - if @job.errors.include?(:other_address)
              small.text-danger.text-nowrap
                = @job.errors.full_messages_for(:other_address).first

        /新規作成と変種時でビューを分岐させる
        .d-flex.justify-content-evenly
          - if action_name == 'new' or action_name == 'create'
            = f.button :type => 'submit', :name => 'post', class: "btn btn-primary btn-rounded" do
              | 公開
            = f.button :type => 'submit', :name => 'draft', class: "btn btn-primary btn-rounded" do
              | 下書き

          - else
            = f.button :type => 'submit', :name => 'post', class: "btn btn-primary btn-rounded" do
              | 公開
            = f.button :type => 'submit', :name => 'draft', class: "btn btn-primary btn-rounded" do
              | 下書き
            button.btn.btn-danger.btn-rounded[data-toggle="modal" data-target="#jobDeletemodal"]
              | 削除

/jpostalは住所自動入力
= render "/jobs/js/jpostal"

/textcounterは文字数カウント
= render "/layouts/js/textcounter", max: 3000

app/views/jobs/draft_index.html.slim
h2.mt-5.mb-3
  strong
    |下書き一覧

= render "/jobs/index", jobs: @jobs
/一覧を呼び出し

app/views/jobs/edit.html.slim
= render "/jobs/info"
= render "/jobs/modals/delete_modal"

app/views/jobs/index.html.slim
h2.mt-5.mb-1
  strong
    | 見つかったバイト

/一覧パーシャル
= render "/jobs/index", jobs: @jobs

/topに戻る
= render "jobs/js/top_btn"

app/views/jobs/new.html.slim
= render "/jobs/info"

app/views/jobs/show.html.slim
/オファー作成モーダル
= render "/offers/modals/offer_modal"

/オファーが既に存在する場合のモーダル
= render "/offers/modals/offer_exist_modal"

.card.job_card.my-5
  = image_tag @job.get_image(2000,1200), class: "card-img-top img-thumbnail"
  .card_body.my-auto
    h2.text-center.mt-3
      strong
        = @job.tytle

    /時給と職種
    .text-center
      h4
        | 時給：
        = @job.hourly_wage
        |  円 /
        = @job.job_type

    /ユーザー情報と紹介文
    .row.px-5.py-3
      .col-lg-2.col-3.text-center
        = link_to user_path(@job.user) do
          = image_tag @job.user.get_image(100,100), class: 'rounded-circle img-thumbnail mt-2 i-fluid'
          p.text-truncate.text-body
            = @job.user.name
      .col-lg-10.col-9.border.rounded-8.bg-light.py-3
        small
          = @job.introduction

    /マップと住所・駅とボタン群
    .row.justify-content-center.p-3.p-lg-5
      .col-lg-6.col-10.order-lg-2
        /マップを呼び出す
        = render "/jobs/js/map", job: @job
      .col-lg-6.col-md-12.my-4.my-lg-auto.order-lg-1
        h6.fw-bold.text-center
          | 所在地：
          = @job.prefecture_code
          = @job.other_address
        h6.fw-bold.text-center
          | 最寄り駅：
          =@job.near_station_line
          |  /
          =@job.near_station
          | 駅

        .my-5.d-flex.justify-content-evenly
          /非同期ブックマークパーシャル
          .bookmark
            = render "/bookmarks/bookmark",job: @job

          /編集ボタンかオファーボタンを分岐表示
          - if @job.user == current_user
            = link_to edit_job_path, class: "btn btn-primary btn-rounded",data: {"turbolinks" => false}, 'data-mdb-toggle': "tooltip", 'title': "編集する" do
              i.fa.fa-pen.fa-2x
          - else
            /オファーかチャットルームが存在する場合はオファー済みモーダルを
            #offer
              = render "offers/offer_button", job: @job

        /自分の投稿だったら共有ボタン表示
        - if @job.user == current_user
          .row.justify-content-center

            p.text-center.text-secondary.text-nowrap
              | ―――――― Share ――――――
            .col-6
              = link_to "https://twitter.com/share?url=#{request.url}/&text=【Part-ner】で#{@job.tytle}のバイト仲間募集中です！&hashtags=Part_ner", class: "btn btn-info btn-rounded btn-block",title: 'Twitter', target: '_blank' , 'data-mdb-toggle': "tooltip", 'title': "Twitterで共有" do
                i.fab.fa-twitter.fa-2x