config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "homes#about"

  devise_for :users,
    skip: [:passwords, :registrations], # いらないルーティングを作らない。sessionとregistration新規のみ。
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_up" => "devise/registrations#new", as: "new_user_registration"
    post "users" => "devise/registrations#create", as: "user_registration"
  end

  resources :users, only:[:show, :edit, :update], param: :account_name # ランダム文字列をidの代わりに使用

  get "jobs/search" => "jobs#search", as: "job_search"
  get "jobs/draft_index" => "jobs#draft_index", as: "job_draft_index"
  resources :jobs, only:[:show, :new, :create, :edit, :update, :destroy], param: :rondom_id # ランダム文字列をidの代わりに使用

  resource :bookmarks, only:[:create,:destroy]
  get "bookmarks" => "bookmarks#index", as: "bookmark_index"
  # resourceだとindexアクションが生成されないため自作。"bookmarks_path"を使おうとするとエラーになるため名前も自作。

  resource :offers, only:[:create,:destroy]
  get "offers" => "offers#index", as: "offers_index"
  # resourceだとindexアクションが生成されないため自作。"offers_paths"を使おうとするとエラーになるため名前も自作。

  resources :chatrooms, only:[:index, :show, :create, :destroy], param: :rondom_id do
    get "change_hide" => "chatrooms#change_hide", as: "change_hide"
  end# ランダム文字列をidの代わりに使用
  resources :messages,only:[:create]

  get "*unmatched_route", to: "application#routing_error", format: false, constraints: lambda { |r|
    # 'rails/active_storage'が含まれているパスはリダイレクト対象外にする
    r.path.exclude? "rails/active_storage"
  }
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
 belongs_to :user
 belongs_to :job
end

app/controllers/offers_controller.rb
# frozen_string_literal: true

class OffersController < ApplicationController
  before_action :ensure_user, only:[:destroy]

  def create
    offer=Offer.new(offer_params)
    offer.user = current_user
    offer.save
    flash.now[:notice] = "オファーを送りました！"
    # メールを作成。deliver_laterでバックグラウンド処理になる
    @from = offer.user
    @job = offer.job
    @content = offer.content
    OfferReceiveMailer.send_mail(@from, @job, @content).deliver_later
  end

  def destroy
    @offer = Offer.find(params[:offer_id])
    @offer.destroy
    flash.now[:alert] = "オファーを削除しました"

    #以下は非同期通信のため追加
    myjobs_ids = Job.where(user_id: current_user.id).pluck(:id)
    @receive_offers = Offer.where(job_id: myjobs_ids) # もらったオファー一覧
    @send_offers = current_user.offers.all # 送ったオファー一覧
  end


  def index
    myjobs_ids = Job.where(user_id: current_user.id).pluck(:id)
    @receive_offers = Offer.where(job_id: myjobs_ids) # もらったオファー一覧
    @send_offers = current_user.offers.all # 送ったオファー一覧
  end

  private
    def offer_params
      params.require(:offer).permit(:content, :job_id)
    end

    def ensure_user
      offer = Offer.find(params[:offer_id])
      unless offer.user == current_user or offer.job.user == current_user
        redirect_back fallback_location: user_path(current_user), flash: {error: "権限がありません。"}
      end
    end

end

app/views/offers/modals/_OKorNG_modal.html.slim
/承認の場合
div id="OKmodal_#{offer.id}" class="modal fade"
  .modal-dialog.modal-dialog-centered
    .modal-content
      .pt-4
        h5.text-center
          strong
            | 承認してDMを始めますか?
      .modal-footer
        = link_to "はじめる", chatrooms_path(offer_id: offer.id, offerer_id: offer.user.id, job_id: offer.job.id), method: :post, class: "btn btn-primary btn-rounded"
        button.btn.btn-secondary.btn-rounded[type="button" data-dismiss="modal"]
          | あとで

/拒否の場合
div id="NGmodal_#{offer.id}" class="modal fade" aria-hidden="true"
  .modal-dialog.modal-dialog-centered
    .modal-content
      .pt-4
        h5.text-center
         strong
            | 削除してよろしいですか？
      .modal-footer
        = link_to "削除する", offers_path(offer_id: offer.id), method: :delete, remote: true, class: "btn btn-danger btn-rounded"
        button.btn.btn-secondary.btn-rounded[type="button" data-dismiss="modal"]
          | あとで

app/views/offers/modals/_delete_modal.html.slim
div id="delete_modal_#{offer.id}" class="modal fade" aria-hidden="true"
  .modal-dialog.modal-dialog-centered
    .modal-content
      .pt-4
        h5.text-center
          strong
            | 削除してよろしいですか？
      .modal-footer
        = link_to "削除する", offers_path(offer_id: offer.id), method: :delete, remote: true, class: "btn btn-danger btn-rounded"
        button.btn.btn-secondary.btn-rounded[type="button" data-dismiss="modal"]
          | あとで

app/views/offers/modals/_offer_exist_modal.html.slim
#offerExistModal.modal.fade[aria-hidden="true"]
  .modal-dialog.modal-dialog-centered
    .modal-content
      .pt-4
        h5.text-center
          strong
            | 既にオファー済みです
      .modal-body

      .modal-footer
        button.btn.btn-secondary.btn-rounded[type="button" data-dismiss="modal"]
          | 閉じる

app/views/offers/modals/_offer_modal.html.slim
#offermodal.modal.fade[aria-hidden="true"]
  .modal-dialog.modal-dialog-centered
    .modal-content
      .pt-4
        h5.text-center
          strong
            | パートナーに立候補しますか？
      = form_with model: Offer.new ,url: offers_path, method: :post, local: false do |f|
        .modal-body
          = f.label :content, "コメント"
          = f.text_area :content, class: "form-control"
          = f.hidden_field :job_id, :value =>@job.id
        .modal-footer
          = f.submit "オファーを送る", class: "btn btn-primary btn-rounded offer_button"
          button.btn.btn-secondary.btn-rounded[type="button" data-dismiss="modal"]
            | 閉じる