config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "homes#about"

  devise_for :users,
    skip: [:passwords, :registrations], # いらないルーティングを作らない。sessionとregistration新規のみ。
    controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_up" => "devise/registrations#new", as: "new_user_registration"
    post "users" => "devise/registrations#create", as: "user_registration"
  end

  resources :users, only:[:show, :edit, :update], param: :account_name # ランダム文字列をidの代わりに使用

  get "jobs/search" => "jobs#search", as: "job_search"
  get "jobs/draft_index" => "jobs#draft_index", as: "job_draft_index"
  resources :jobs, only:[:show, :new, :create, :edit, :update, :destroy], param: :rondom_id # ランダム文字列をidの代わりに使用

  resource :bookmarks, only:[:create,:destroy]
  get "bookmarks" => "bookmarks#index", as: "bookmark_index"
  # resourceだとindexアクションが生成されないため自作。"bookmarks_path"を使おうとするとエラーになるため名前も自作。

  resource :offers, only:[:create,:destroy]
  get "offers" => "offers#index", as: "offers_index"
  # resourceだとindexアクションが生成されないため自作。"offers_paths"を使おうとするとエラーになるため名前も自作。

  resources :chatrooms, only:[:index, :show, :create, :destroy], param: :rondom_id do
    get "change_hide" => "chatrooms#change_hide", as: "change_hide"
  end# ランダム文字列をidの代わりに使用
  resources :messages,only:[:create]

  get "*unmatched_route", to: "application#routing_error", format: false, constraints: lambda { |r|
    # 'rails/active_storage'が含まれているパスはリダイレクト対象外にする
    r.path.exclude? "rails/active_storage"
  }
end

app/views/layouts/_header.html.slim
header.shadow-sm.sticky-top.bg-info
  nav.navbar.navbar-expand-lg.navbar-light.p-1
    .container

      /ロゴ部分。Aboutページでだけマイページリンク表示
      .d-flex.align-items-center
        a.navbar-brand[href="/"]
          = image_tag 'Part-ner.png', size: "60x60"
        - if user_signed_in? && action_name == "about"
          = link_to 'マイページへ', user_path(current_user), class: "btn btn-secondary btn-rounded nav-item"

      /メニュー
      #navbarNavDropdown.collapse.navbar-collapse
        ul.navbar-nav.ml-auto.ms-auto
          /サインインしてるとき
          - if user_signed_in?
            button.btn.btn-secondary.btn-rounded.nav-item.ms-auto.m-2[data-toggle="modal" data-target="#searchModal"]
              |  バイトを探す

            /ドロップダウン。下書きと新規
            .dropdown.nav-item.ms-auto.m-2
              button#dropdownMenuButton.btn.btn-secondary.rounded-pill.dropdown-toggle[type="button" data-mdb-toggle="dropdown" aria-expanded="false"]
                |  パートナー募集
              ul.dropdown-menu[aria-labelledby="dropdownMenuButton"]
                li
                  = link_to "新規募集",new_job_path, class: 'dropdown-item',data: {"turbolinks" => false}
                li
                  = link_to "下書き一覧",job_draft_index_path, class: 'dropdown-item'
            button.btn.btn-secondary.rounded-pill.nav-item.ms-auto.m-2[data-toggle="modal" data-target="#Logoutmodal"]
              |  ログアウト

          /サインインしてないとき
          - else
            = link_to "新規登録", new_user_registration_path, class: 'nav-item ms-auto btn btn-secondary btn-rounded nav-item ms-auto m-2'
            = link_to "ログイン", new_user_session_path, class: 'nav-item ms-auto btn btn-secondary btn-rounded nav-item ms-auto m-2'

      /ハンバーガーメニュー
      button.navbar-toggler.ms-auto[type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"]
        i.fas.fa-bars.fa-lg

  /フラッシュメッセージをヘッダー直下に出すためheaderタグ内に記述
  #flash.container
    = render "/layouts/js/flash"

/検索モーダルとログアウト確認モーダル
= render "layouts/modals/search_modal"
= render "layouts/modals/logout_modal"

app/views/layouts/_sidebar.html.slim
.sidebar.col-lg-3.d-lg-block.d-none
  /サイドバーをいい位置で固定
  div[style="position: sticky; top: 127px;"]

    /プロフィール画像
    #user_img.card.rounded-9.my-5[data-turbolinks-permanent]
      = link_to user_path(current_user),class: "mx-auto text-center text-body" do
        = image_tag current_user.get_image(70,70), class: 'rounded-circle my-2 img-thumbnail img-fluid'
        h5
          strong
            = current_user.name.truncate(9)

    /リンクリスト
    .list-group.list-group-light.mt-3
      h6
        strong
          = link_to user_path(current_user), class: "list-group-item list-group-item-action text-truncate px-4 mb-3 rounded-pill user_tab" do
            i.far.fa-user.fa-lg.fa-fw
            |  プロフィール

      h6
        strong
          = link_to chatrooms_path, class: "list-group-item list-group-item-action text-truncate  px-4 mb-3 rounded-pill #{active_if('chatrooms')}" do
            i.far.fa-comment-dots.fa-lg.fa-fw
            |  メッセージ

            /通知バッジの処理。存在する場合のみ件数表示
            - if Message.unread_by(current_user).exists?
              span.badge.badge-danger.rounded-pill
                = Message.unread_by(current_user).count
      h6
        strong
          = link_to offers_index_path, class: "list-group-item list-group-item-action text-truncate  px-4 mb-3 rounded-pill #{active_if('offers')}" do
            i.far.fa-handshake.fa-lg.fa-fw
            |  オファー

            /通知バッジの処理。存在する場合のみ件数表示
            - if Offer.where(job_id: current_user.jobs.ids).exists?
              span.badge.badge-danger.rounded-pill
                = Offer.where(job_id: current_user.jobs.ids).count
      h6
        strong
          = link_to bookmark_index_path,class: "list-group-item list-group-item-action text-truncate  px-4 mb-3 rounded-pill #{active_if('bookmarks')}" do
            i.far.fa-bookmark.fa-lg.fa-fw
            |  ブックマーク

      h6.mt-5
        strong
          = link_to :back, class: "list-group-item list-group-item-action text-truncate  px-4 mb-3 rounded-pill" do
            i.fas.fa-arrow-left.fa-lg.fa-fw
            |  戻る


/ボトムバー
.bottomber.list-group.list-group-light.flex-row.justify-content-evenly.align-items-end.bg-secondary.d-lg-none.order-md-2.fixed-bottom.p-0
  h6
    = link_to user_path(current_user), class: "list-group-item list-group-item-action px-3 m-auto rounded-9 user_tab" do
      i.far.fa-user.fa-lg.fa-fw
  h6
    = link_to chatrooms_path, class: "list-group-item list-group-item-action position-relative px-3 m-auto rounded-9 #{active_if('chatrooms')}" do
      i.far.fa-comment-dots.fa-lg.fa-fw
      /通知バッジの処理。存在する場合のみ件数表示
      - if Message.unread_by(current_user).exists?
        span.position-absolute.top-0.start-100.translate-middle.badge.rounded-pill.badge-danger
          = Message.unread_by(current_user).count

  h6
    /クラス名にif分を噛ませるときはclass=""で書く。コントローラーjobsかつアクションがsearchの時だけアクティブに
    a class="list-group-item list-group-item-action px-3 m-auto rounded-9 #{active_if('jobs') if action_name == "search"} " data-toggle="modal" data-target="#searchModal"
      i.far.fa-dot-circle.fa-lg.fa-fw

  h6
    = link_to offers_index_path, class: "list-group-item list-group-item-action position-relative px-3 m-auto rounded-9 #{active_if('offers')}" do
      i.far.fa-handshake.fa-lg.fa-fw
      /通知バッジの処理。存在する場合のみ件数表示
      - if Offer.where(job_id: current_user.jobs.ids).exists?
        span.position-absolute.top-0.start-100.translate-middle.badge.rounded-pill.badge-danger
          = Offer.where(job_id: current_user.jobs.ids).count
  h6
    strong
      = link_to bookmark_index_path,class: "list-group-item list-group-item-action px-3 m-auto rounded-9 #{active_if('bookmarks')}" do
        i.far.fa-bookmark.fa-lg.fa-fw


/非表示。スクリプトにデータを渡す用
#current_info.d-none[data-current_user_id="#{current_user.id}"]

/サイドバーの動きスクリプト
= render "/layouts/js/side_animate"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Part-ner
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag('favicon.ico')
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    script[src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"]

  body
    = render "layouts/header"
    .container
      .row.justify-content-evenly
        /サイドバーはログイン時で、ホームコントローラ以外
        - if user_signed_in? && controller_path != "homes"
          = render "layouts/sidebar", current: false

        #contents.col-lg-8.col-md-12
          = yield